### ISSUE TITLE
ERROR TRYING ON UBUNTU

### ISSUE THREAD

**Issue by usarral** [horacehylee/gcalendar-cli#2]
─ sudo gcal setup                  
[sudo] contraseña para usarr: 
(node:24611) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/root/client_secret.json'
(node:24611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by horacehylee** [comment]
Hi @usarral,

The package is using `os.homedir()` for finding the `client_secret.json` and `calendar_api_token.json` file.
Could you not use `sudo` for the command? As `sudo` will point to the root folder for homedir().
